baseURL = "/"
languageCode = "en-us"
title = "Airspace for Hugo"
theme = "airspace-hugo"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[menu]

  [[menu.header]]
    weight = 2
    name = "Blog"
    url = "/blog"
  [[menu.header]]
    weight = 3
    name = "Github"
    url = "https://www.github.com/thom1178"
  [[menu.header]]
    weight = 4
    name = "Twitter"
    url = "https://www.twitter.com/emptyjamel"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "How it works"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "Blog"
    url = "#"
  [[menu.footer]]
    weight = 5
    name = "Terms"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "A small data directory"
    subtitle = ""

  [params.wrapper]
    enable = true
    title = "About"
    italic = '"Hiding within those mounds of data is knowledge that could change the life of a patient, or change the world." - Atul Butte, Stanford '
    paragraph = "I'm Jamel. This blog is about statistics, R, data science and pretty graphs. Sometimes I get interested in a particular topic, and can't get the thing out of my head until I've done some digging. Many of the things on this site is authored by me, but I reference those items that are not. You can find me on linkedin, github, and twitter. The latter is not so much career based, but has funny memes."

  [params.blog]
    enable = true
    title = "Get The Latest"
    subtitle = ""

  [params.feature]
    enable = true
    title = "methodolgy"
    content = "The beautiful thing about data analysis is that a lot of the time, there is not a singe right answer. A model I build could be different than one you build. Therefore, the methodolgy is the most important aspect to any analysis. In order for me to understand your results, I have to know how you got there. This is how I got here."
    [params.feature.button]
      caption = "Resume"
      url = "about/resume.pdf"

  [params.call]
    enable = true
    title = ""
    paragraph = ""

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don't just take our word for it. Check out some of our latest work."
    [params.contact.box]
      title = ""
      address = "Ontario, CA"
      email = "Email: contact@jamelt.com"
    [params.contact.gmaps]
      title = "Where I currently Live"
      